version: '3'

volumes:
  microservice_postgres_data:

services:
  api-gateway:
    image: gamel-api-gateway
    build:
      context: ./apps/gamel-api-gateway
      dockerfile: dockerfile
    container_name: gamel-api-gateway
    depends_on:
      - user-service
      - video-service
      - analytics-service
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./apps/gamel-api-gateway/src:/usr/src/app/src:z
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - STAGE=local
      - POSTGRES_HOST=host.docker.internal
    restart: "no"

  user-service:
    image: gamel-user-service
    build:
      context: ./apps/user
      dockerfile: dockerfile
    container_name: gamel-user-service
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./apps/user/src:/usr/src/app/src:z
    environment:
      - PORT=3001
      - STAGE=local
      - POSTGRES_HOST=host.docker.internal
    restart: "no"

  video-service:
    image: gamel-video-service
    build:
      context: ./apps/video
      dockerfile: dockerfile
    container_name: gamel-video-service
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./apps/video/src:/usr/src/app/src:z
    environment:
      - PORT=3002
      - STAGE=local
      - POSTGRES_HOST=host.docker.internal
    restart: "no"

  analytics-service:
    image: gamel-analytics-service
    build:
      context: ./apps/video
      dockerfile: dockerfile
    container_name: gamel-analytics-service
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./apps/analytics/src:/usr/src/app/src:z
    environment:
      - PORT=3003
      - STAGE=local
      - POSTGRES_HOST=host.docker.internal
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    restart: "no"
