FROM node:23.9.0

WORKDIR /usr/src/app

RUN npm install -g @nestjs/cli

# Copy application dependency manifests to the container image.
# Copying this first prevents re-running npm install on every code change.
COPY package*.json ./

COPY . .

CMD npm install && nodemon --watch src --exec "nest start"
